# Numpy - 1

In [131]:
import numpy as np 

In [132]:
a = [1,2,3,4,5,6]

In [133]:
[i**2 for i in a]

[1, 4, 9, 16, 25, 36]

In [134]:
# Calculating the square now using numpy 

In [135]:
b = np.array([1,2,3,4,5,6]) # Numpy is used to do the element wise operations like this 

In [136]:
b**2

array([ 1,  4,  9, 16, 25, 36], dtype=int32)

In [137]:
l = range(10000000)

In [138]:
%timeit [i**2 for i in l]

2.52 s ± 90 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [139]:
np_l = np.arange(10000000)

In [140]:
%timeit np_l**2

12.5 ms ± 952 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# How to create a Numpy array 

In [141]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

# What is the dimension of the arr1 

In [142]:
arr1.ndim ## This gives the dimension of the array.

1

# what is the shape of the arr1

In [143]:
arr1.shape ## Gives the shape(rows and columns) of the array

(4,)

# Giving equal spaces in the line using linspace.

In [144]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [145]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# Type of a numpy array

In [326]:
type(arr1)

numpy.ndarray

# Numpy arrays can only store one type of data 

In [147]:
np.array([1,2,3,4,5]) # This works because only integer values are given in the array.

array([1, 2, 3, 4, 5])

In [148]:
np.array([1.3,2.6,2.7,3.5,49,4.7]) # This works because only the floating point values are given in the array.

array([ 1.3,  2.6,  2.7,  3.5, 49. ,  4.7])

In [149]:
np.array([1,2,4,5.7,9.3,2,6.5]) # This works by converting all the values of the array to floating values as numpy can only,
                                # store a single type of data, and gives the output without lossing the data.

array([1. , 2. , 4. , 5.7, 9.3, 2. , 6.5])

# Converting all the values of the array to integers

In [150]:
np.array([1,2,4,5.7,9.3,2,6.5] , dtype = "int")

array([1, 2, 4, 5, 9, 2, 6])

# Converting all the values to float

In [307]:
np.array([1,2,4,5.7,9.3,2,6.5] , dtype = "float") # In this case even if we do not specify the dtype to float,  
                                                # numpy automatically conversts all the integeres to floating values.

array([1. , 2. , 4. , 5.7, 9.3, 2. , 6.5])

# 2D Arrays(Matrices)

In [152]:
m1 = np.array([[1,2,3],[4,5,6]])

In [153]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

# Shape of m1

In [154]:
m1.shape

(2, 3)

# Dimesnion of m1

In [155]:
m1.ndim

2

In [156]:
# What will be the answer for the following??

In [157]:
A = np.array([[2,3,4] , [1,4,5] , [8,9,5]])
b = len(A)
b

3

# What will be the shape of A

In [158]:
A.shape

(3, 3)

# What will be the dimension of A

In [159]:
A.ndim 

2

# Convert the 1-D array to (3X4) 2-D array

In [160]:
m2 = np.arange(1,13)
m2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [161]:
m2.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Convert m2 to a (4x3) 2-D array

In [162]:
m3 = m2.reshape(4,3)

In [163]:
m3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [164]:
m3.shape

(4, 3)

In [165]:
m3.ndim

2

In [166]:
m3.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [167]:
m3.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

# Transpose of an array 

In [168]:
a = np.arange(3)
a

array([0, 1, 2])

In [169]:
# To perform the transpose following should be done 

In [170]:
a.T

array([0, 1, 2])

# Note - Transpose works on the 2-D arrays, but not the 1-D arrays. 

In [171]:
A = np.array([[1,2,3] , [3,4,5]])
A

array([[1, 2, 3],
       [3, 4, 5]])

In [172]:
# Applying transpose on the matrix

In [173]:
A.T

array([[1, 3],
       [2, 4],
       [3, 5]])

In [174]:
L = np.arange(12)
L

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [175]:
L.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [176]:
L.reshape(6,-1) # "-1" actually takes the rows given and distributes all the column values equally with respect to the rows.

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [177]:
L.reshape(4,-1) # "-1" actually takes the rows given and distributes all the column values equally with respect to the rows.

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [178]:
L.reshape(3,-1) # "-1" actually takes the rows given and distributes all the column values equally with respect to the rows.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [179]:
L.reshape(6,-2) # "-2" actually takes the rows given and distributes all the column values equally with respect to the rows.

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [180]:
L.reshape(-2,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Note - In the above, Any negative value given above in the reshape actually takes the rows given and distributes all the column values equally with respect to the rows. And also works same in the reverse too. 

# Creating some special numpy arrays

# Creating a matrix of all zeros

In [181]:
np.zeros(4) # Creating a 1-D array of all zeros

array([0., 0., 0., 0.])

In [182]:
np.zeros([4,4]) # Creating a 2-D array of all zeros with shape(4x4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [183]:
np.zeros([2,3]) # Creating a 2-D array of all zeros with shape(2x3)

array([[0., 0., 0.],
       [0., 0., 0.]])

# Creating a matrix of all ones.

In [184]:
np.ones(5) # Creating a 1-D array of all ones

array([1., 1., 1., 1., 1.])

In [308]:
np.ones([5,5] , dtype = "int") # Creating  2-D array of all ones with shape(5x5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [186]:
np.ones([2,3]) # Creating a 2-D array of all ones with shape(2x3)

array([[1., 1., 1.],
       [1., 1., 1.]])

# Create a matrix filling up with certain number 

In [187]:
np.full([2,3] , 5) # Fills up the matrix of size (2x3) with all 5's.

array([[5, 5, 5],
       [5, 5, 5]])

In [188]:
np.full([6,6] , 10)

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [189]:
np.full([20,20] , 24) 

array([[24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
        24, 24, 24, 24],
       [24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
        24, 24, 24, 24],
       [24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
        24, 24, 24, 24],
       [24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
        24, 24, 24, 24],
       [24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
        24, 24, 24, 24],
       [24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
        24, 24, 24, 24],
       [24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
        24, 24, 24, 24],
       [24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
        24, 24, 24, 24],
       [24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
        24, 24, 24, 24],
       [24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
        24, 24, 24, 24],
       [24, 24, 24, 24, 24, 24

# Creating an Identity matrix

In [190]:
np.identity(10) # We do not need to give the shape because giving "10" automatically make it a (10x10) square matrix.

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [312]:
np.identity(5) # Giving 5 to identity makes it gives us a (5x5) identity matrix.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [310]:
np.identity(4) # Giving 4 to identity makes it gives us a (5x5) identity matrix.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [313]:
np.identity(2) # Giving 2 to identity makes it gives us a (5x5) identity matrix.

array([[1., 0.],
       [0., 1.]])

# Creating a Diagnol matrix

In [191]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [192]:
np.diag([3,5,9,11,34,67])

array([[ 3,  0,  0,  0,  0,  0],
       [ 0,  5,  0,  0,  0,  0],
       [ 0,  0,  9,  0,  0,  0],
       [ 0,  0,  0, 11,  0,  0],
       [ 0,  0,  0,  0, 34,  0],
       [ 0,  0,  0,  0,  0, 67]])

In [193]:
S = np.diag([3,4,5,6,7,8])
S

array([[3, 0, 0, 0, 0, 0],
       [0, 4, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0],
       [0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 8]])

In [194]:
np.diag(S)

array([3, 4, 5, 6, 7, 8])

# Indexing and slicing 

In [198]:
l1 = np.arange(12)
l1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Accessing the value 2,7,5 from the above list with the index

In [199]:
l1[2]

2

In [200]:
l[7]

7

In [201]:
l1[5]

5

# Accesing the index 12 which is out of range

In [315]:
l1[12] # As the given index is out of range for the above numpy array, error occurs.

IndexError: index 12 is out of bounds for axis 0 with size 12

# Creating the 2D array of the above list 

In [205]:
l1.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [318]:
c1 = np.arange(1,10).reshape(3,3)
c1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# How to access the value 6 from the above 2D array

# Method-1

In [229]:
c1[1][2]

6

# Method-2

In [237]:
c1[1,2] # Use this method always.

6

# How to access the value 9 from the above 2D array

# Method1

In [231]:
c1[2][2]

9

In [238]:
c1[2,2] #Use this method always 

9

# How to access the value 1 from the above 2D Array

In [233]:
c1[0][0]

1

In [239]:
c1[0,0] # Use this method always

1

# How to access the value 8 from the abobe 2D array

In [235]:
c1[2][1]

8

In [240]:
c1[2,1] #Use this method always 

8

# What will be the output of c1[1][1]

In [241]:
c1[1][1]

5

In [242]:
c1[1,1]

5

# Accessing the multiple values at a time using the indices

In [245]:
c2 = np.array([100,200,300,400,500,600,700,800])

In [246]:
c2[[1,0,3,2,4,5,2,7]]

array([200, 100, 400, 300, 500, 600, 300, 800])

# Accessing multiple values of 2D array using the indices

In [247]:
c3 = np.arange(9).reshape(3,3)
c3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Access the values 0,4,8 from the above 2D array

In [249]:
c3[[0,1,2] , [0,1,2]]

array([0, 4, 8])

# Access the values 2,5,8 form the above 2D array 

In [319]:
c3[[0,1,2] , 2]

array([2, 5, 8])

# Access the values 3,1,2,8,7 from the above 2D array

In [251]:
c3[[1,0,0,2,2] , [0,1,2,2,1]]

array([3, 1, 2, 8, 7])

# Access the values 5,3,1,7 from the above 2D array 

In [252]:
c3[[1,1,0,2] , [2,0,1,1]]

array([5, 3, 1, 7])

#  ##** Slicing

#  Very Important Slicing technique - Fancy indexing 

In [255]:
c4 = np.arange(12)
c4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Slice the first five elements from the above 

In [258]:
c4[0:5]

array([0, 1, 2, 3, 4])

In [260]:
c4[:5] # same method. Do not need to mention the starting index if we are slicing form the very beggining of the array.

array([0, 1, 2, 3, 4])

# Slice the values from the value 2 to the last value.

In [263]:
c4[2:12]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [265]:
c4[2:] #Same method. Do not need to mention the last value index if we are slicing till the last 

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Slice the values from 3 to 8 from the abobe array 

In [268]:
c4[3:9]

array([3, 4, 5, 6, 7, 8])

# Slicing of 2D arrays

In [270]:
c5 = np.arange(12).reshape(3,4)
c5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [321]:
c5[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

# Access fthe elements 1,2,5,6,9,10 from the above 2D array

In [272]:
c5[0: , 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

# Access the elements 0,5,6,11 from the above 2D array

In [275]:
c5[[0,1,1,2] , [0,1,2,3]]

array([ 0,  5,  6, 11])

# Access the elements 0,4,8 from the above 2D array

In [276]:
c5[0: , :1]

array([[0],
       [4],
       [8]])

In [277]:
c5[0,1:3]

array([1, 2])

In [278]:
c5[0: , 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [279]:
c5[1: , 1:3]

array([[ 5,  6],
       [ 9, 10]])

# Write slicing code to extract 2,3,6,7,10,11

In [283]:
c5[0: , 2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [284]:
c5[: , 2:] # Other way of slicing to get the required values 

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

# Write a Slicing code to extract the values 1,3,5,7,9,11

In [285]:
c5[: , [1,3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

# What will be the output of the following code snippet 

In [286]:
c6 = np.array([0,1,2,3,4,5,6,7])
c6[4:] = 10

In [287]:
c6

array([ 0,  1,  2,  3, 10, 10, 10, 10])

# What will be the output for following code snippet.

In [288]:
A = np.array([1,2,3,4,5])
B = np.array([8,7,6])

In [289]:
A [2:] = B[::-1]

In [290]:
A

array([1, 2, 6, 7, 8])

# Fancy indexing 

In [291]:
c7 = np.arange(12).reshape(3,4)
c7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [292]:
c7<6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [293]:
c7[c7<6]

array([0, 1, 2, 3, 4, 5])

In [322]:
[c7%2 == 0] 

[array([[ True, False,  True, False],
        [ True, False,  True, False],
        [ True, False,  True, False]])]

In [324]:
c7[c7%2 == 0]

array([ 0,  2,  4,  6,  8, 10])

# We can give two conditions too in fancy indexing  ??

In [299]:
c7[(c7%2==0) & (c7%5==0)]

array([ 0, 10])

# What would be the output of following code snippet 

In [306]:
A = np.array([0,1,2,3,4,5])
mask = (A%2 == 0)
print(mask)
A[mask] = -1
A

[ True False  True False  True False]


array([-1,  1, -1,  3, -1,  5])